### ISSUE TITLE
ValueError: Single '{' encountered in format string

### ISSUE THREAD

**Issue by SimonGreenhill** [clld/glottolog#277]
There's a stray "{" being generated somewhere -- 

```shell
glottolog show zarm1239
```

```python
Traceback (most recent call last):
  File "/Users/simon/.pyenv/versions/3.7.0/bin/glottolog", line 11, in <module>
    load_entry_point('pyglottolog', 'console_scripts', 'glottolog')()
  File "/Users/simon/src/glottolog/pyglottolog/__main__.py", line 32, in main
    sys.exit(parser.main())
  File "/Users/simon/.pyenv/versions/3.7.0/lib/python3.7/site-packages/clldutils/clilib.py", line 110, in main
    catch_all=catch_all, parsed_args=args)
  File "/Users/simon/.pyenv/versions/3.7.0/lib/python3.7/site-packages/clldutils/clilib.py", line 82, in main
    self.commands[args.command](args)
  File "/Users/simon/.pyenv/versions/3.7.0/lib/python3.7/site-packages/clldutils/clilib.py", line 35, in __call__
    return self.func(args)
  File "/Users/simon/src/glottolog/pyglottolog/commands.py", line 217, in show
    sprint(line, None, attrs=['bold'] if line.startswith('[') else [])
  File "/Users/simon/src/glottolog/pyglottolog/util.py", line 19, in sprint
    text = text.format(*args)
ValueError: Single '{' encountered in format string

```

**Comment by xrotwang** [comment]
Must be this: https://github.com/clld/glottolog/blob/cfd73ebc8824ed7f70c7b062f5d5da578ecde431/languoids/tree/song1307/east2431/zarm1240/zarm1239/md.ini#L82

**Comment by d97hah** [comment]
The trigger keywords have no real illegal characters in them as they were
produced, but some chars mean something to Python. Anyway, I removed this
one because it was superfluos anyway.

Pada tanggal Sel, 13 Nov 2018 pukul 11.45 Robert Forkel <
notifications@github.com> menulis:
